kind: Deployment
apiVersion: apps/v1
metadata:
  name: exchange
spec:
  selector:
    matchLabels:
      app: exchange
  replicas: 1
  template:
    metadata:
      labels:
        app: exchange
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
    spec:
      containers:
        - name: exchange
          image: quay.io/youruser/ossm-exchange-traced:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080